name: Dr Buhler .com 
description: >
    Draft
about: >
    A new one page directory 

master_repo: false
url: "http://drbuhler.com"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           Dr Buhler 
  avatar:         "db_fj_graduation.jpg"
  email:          "dionysiusbuhler@gmail.com"
  # Social networking links used in footer. Update and remove as you like.
  twitter: dionysiusbuhler
  github: https://github.com/drbuhler
  linkedin: https://www.linkedin.com/in/dionysiusbuhler
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
